; Auto-generated. Do not edit!


(cl:in-package prac_ros-msg)


;//! \htmlinclude timebackFeedback.msg.html

(cl:defclass <timebackFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:float
    :initform 0.0))
)

(cl:defclass timebackFeedback (<timebackFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <timebackFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'timebackFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name prac_ros-msg:<timebackFeedback> is deprecated: use prac_ros-msg:timebackFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <timebackFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader prac_ros-msg:progress-val is deprecated.  Use prac_ros-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <timebackFeedback>) ostream)
  "Serializes a message object of type '<timebackFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <timebackFeedback>) istream)
  "Deserializes a message object of type '<timebackFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<timebackFeedback>)))
  "Returns string type for a message object of type '<timebackFeedback>"
  "prac_ros/timebackFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'timebackFeedback)))
  "Returns string type for a message object of type 'timebackFeedback"
  "prac_ros/timebackFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<timebackFeedback>)))
  "Returns md5sum for a message object of type '<timebackFeedback>"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'timebackFeedback)))
  "Returns md5sum for a message object of type 'timebackFeedback"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<timebackFeedback>)))
  "Returns full string definition for message of type '<timebackFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'timebackFeedback)))
  "Returns full string definition for message of type 'timebackFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <timebackFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <timebackFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'timebackFeedback
    (cl:cons ':progress (progress msg))
))
