; Auto-generated. Do not edit!


(cl:in-package prac_ros-msg)


;//! \htmlinclude timebackGoal.msg.html

(cl:defclass <timebackGoal> (roslisp-msg-protocol:ros-message)
  ((dish_count
    :reader dish_count
    :initarg :dish_count
    :type cl:integer
    :initform 0))
)

(cl:defclass timebackGoal (<timebackGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <timebackGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'timebackGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name prac_ros-msg:<timebackGoal> is deprecated: use prac_ros-msg:timebackGoal instead.")))

(cl:ensure-generic-function 'dish_count-val :lambda-list '(m))
(cl:defmethod dish_count-val ((m <timebackGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader prac_ros-msg:dish_count-val is deprecated.  Use prac_ros-msg:dish_count instead.")
  (dish_count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <timebackGoal>) ostream)
  "Serializes a message object of type '<timebackGoal>"
  (cl:let* ((signed (cl:slot-value msg 'dish_count)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <timebackGoal>) istream)
  "Deserializes a message object of type '<timebackGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'dish_count) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<timebackGoal>)))
  "Returns string type for a message object of type '<timebackGoal>"
  "prac_ros/timebackGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'timebackGoal)))
  "Returns string type for a message object of type 'timebackGoal"
  "prac_ros/timebackGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<timebackGoal>)))
  "Returns md5sum for a message object of type '<timebackGoal>"
  "504f457a172a93818f1eb3d89ab1a81a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'timebackGoal)))
  "Returns md5sum for a message object of type 'timebackGoal"
  "504f457a172a93818f1eb3d89ab1a81a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<timebackGoal>)))
  "Returns full string definition for message of type '<timebackGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 dish_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'timebackGoal)))
  "Returns full string definition for message of type 'timebackGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 dish_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <timebackGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <timebackGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'timebackGoal
    (cl:cons ':dish_count (dish_count msg))
))
