; Auto-generated. Do not edit!


(cl:in-package prac_ros-msg)


;//! \htmlinclude timebackResult.msg.html

(cl:defclass <timebackResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil)
   (result_message
    :reader result_message
    :initarg :result_message
    :type cl:string
    :initform ""))
)

(cl:defclass timebackResult (<timebackResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <timebackResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'timebackResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name prac_ros-msg:<timebackResult> is deprecated: use prac_ros-msg:timebackResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <timebackResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader prac_ros-msg:success-val is deprecated.  Use prac_ros-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'result_message-val :lambda-list '(m))
(cl:defmethod result_message-val ((m <timebackResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader prac_ros-msg:result_message-val is deprecated.  Use prac_ros-msg:result_message instead.")
  (result_message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <timebackResult>) ostream)
  "Serializes a message object of type '<timebackResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'result_message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'result_message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <timebackResult>) istream)
  "Deserializes a message object of type '<timebackResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result_message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'result_message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<timebackResult>)))
  "Returns string type for a message object of type '<timebackResult>"
  "prac_ros/timebackResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'timebackResult)))
  "Returns string type for a message object of type 'timebackResult"
  "prac_ros/timebackResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<timebackResult>)))
  "Returns md5sum for a message object of type '<timebackResult>"
  "653d7c58e227d73c141a202e6fd40f04")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'timebackResult)))
  "Returns md5sum for a message object of type 'timebackResult"
  "653d7c58e227d73c141a202e6fd40f04")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<timebackResult>)))
  "Returns full string definition for message of type '<timebackResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%string result_message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'timebackResult)))
  "Returns full string definition for message of type 'timebackResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%string result_message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <timebackResult>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'result_message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <timebackResult>))
  "Converts a ROS message object to a list"
  (cl:list 'timebackResult
    (cl:cons ':success (success msg))
    (cl:cons ':result_message (result_message msg))
))
