// Auto-generated. Do not edit!

// (in-package prac_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class timebackGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dish_count = null;
    }
    else {
      if (initObj.hasOwnProperty('dish_count')) {
        this.dish_count = initObj.dish_count
      }
      else {
        this.dish_count = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type timebackGoal
    // Serialize message field [dish_count]
    bufferOffset = _serializer.int32(obj.dish_count, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type timebackGoal
    let len;
    let data = new timebackGoal(null);
    // Deserialize message field [dish_count]
    data.dish_count = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'prac_ros/timebackGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '504f457a172a93818f1eb3d89ab1a81a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 dish_count
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new timebackGoal(null);
    if (msg.dish_count !== undefined) {
      resolved.dish_count = msg.dish_count;
    }
    else {
      resolved.dish_count = 0
    }

    return resolved;
    }
};

module.exports = timebackGoal;
