// Generated by gencpp from file prac_ros/jdk.msg
// DO NOT EDIT!


#ifndef PRAC_ROS_MESSAGE_JDK_H
#define PRAC_ROS_MESSAGE_JDK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prac_ros
{
template <class ContainerAllocator>
struct jdk_
{
  typedef jdk_<ContainerAllocator> Type;

  jdk_()
    : answer(0.0)
    , jiangdakun()  {
    }
  jdk_(const ContainerAllocator& _alloc)
    : answer(0.0)
    , jiangdakun(_alloc)  {
  (void)_alloc;
    }



   typedef float _answer_type;
  _answer_type answer;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _jiangdakun_type;
  _jiangdakun_type jiangdakun;





  typedef boost::shared_ptr< ::prac_ros::jdk_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prac_ros::jdk_<ContainerAllocator> const> ConstPtr;

}; // struct jdk_

typedef ::prac_ros::jdk_<std::allocator<void> > jdk;

typedef boost::shared_ptr< ::prac_ros::jdk > jdkPtr;
typedef boost::shared_ptr< ::prac_ros::jdk const> jdkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prac_ros::jdk_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prac_ros::jdk_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prac_ros::jdk_<ContainerAllocator1> & lhs, const ::prac_ros::jdk_<ContainerAllocator2> & rhs)
{
  return lhs.answer == rhs.answer &&
    lhs.jiangdakun == rhs.jiangdakun;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prac_ros::jdk_<ContainerAllocator1> & lhs, const ::prac_ros::jdk_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prac_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prac_ros::jdk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prac_ros::jdk_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prac_ros::jdk_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prac_ros::jdk_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prac_ros::jdk_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prac_ros::jdk_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prac_ros::jdk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcf325aad560bddf55f9bd3131b03903";
  }

  static const char* value(const ::prac_ros::jdk_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcf325aad560bddfULL;
  static const uint64_t static_value2 = 0x55f9bd3131b03903ULL;
};

template<class ContainerAllocator>
struct DataType< ::prac_ros::jdk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prac_ros/jdk";
  }

  static const char* value(const ::prac_ros::jdk_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prac_ros::jdk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 answer\n"
"string jiangdakun\n"
;
  }

  static const char* value(const ::prac_ros::jdk_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prac_ros::jdk_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
      stream.next(m.jiangdakun);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jdk_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prac_ros::jdk_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prac_ros::jdk_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "answer: ";
    Printer<float>::stream(s, indent + "  ", v.answer);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "jiangdakun: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.jiangdakun);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRAC_ROS_MESSAGE_JDK_H
