// Generated by gencpp from file prac_ros/SrvJdk.msg
// DO NOT EDIT!


#ifndef PRAC_ROS_MESSAGE_SRVJDK_H
#define PRAC_ROS_MESSAGE_SRVJDK_H

#include <ros/service_traits.h>


#include <prac_ros/SrvJdkRequest.h>
#include <prac_ros/SrvJdkResponse.h>


namespace prac_ros
{

struct SrvJdk
{

typedef SrvJdkRequest Request;
typedef SrvJdkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvJdk
} // namespace prac_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prac_ros::SrvJdk > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::prac_ros::SrvJdk&) { return value(); }
};

template<>
struct DataType< ::prac_ros::SrvJdk > {
  static const char* value()
  {
    return "prac_ros/SrvJdk";
  }

  static const char* value(const ::prac_ros::SrvJdk&) { return value(); }
};


// service_traits::MD5Sum< ::prac_ros::SrvJdkRequest> should match
// service_traits::MD5Sum< ::prac_ros::SrvJdk >
template<>
struct MD5Sum< ::prac_ros::SrvJdkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prac_ros::SrvJdk >::value();
  }
  static const char* value(const ::prac_ros::SrvJdkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prac_ros::SrvJdkRequest> should match
// service_traits::DataType< ::prac_ros::SrvJdk >
template<>
struct DataType< ::prac_ros::SrvJdkRequest>
{
  static const char* value()
  {
    return DataType< ::prac_ros::SrvJdk >::value();
  }
  static const char* value(const ::prac_ros::SrvJdkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prac_ros::SrvJdkResponse> should match
// service_traits::MD5Sum< ::prac_ros::SrvJdk >
template<>
struct MD5Sum< ::prac_ros::SrvJdkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prac_ros::SrvJdk >::value();
  }
  static const char* value(const ::prac_ros::SrvJdkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prac_ros::SrvJdkResponse> should match
// service_traits::DataType< ::prac_ros::SrvJdk >
template<>
struct DataType< ::prac_ros::SrvJdkResponse>
{
  static const char* value()
  {
    return DataType< ::prac_ros::SrvJdk >::value();
  }
  static const char* value(const ::prac_ros::SrvJdkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRAC_ROS_MESSAGE_SRVJDK_H
