// Generated by gencpp from file prac_ros/SrvJdkResponse.msg
// DO NOT EDIT!


#ifndef PRAC_ROS_MESSAGE_SRVJDKRESPONSE_H
#define PRAC_ROS_MESSAGE_SRVJDKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prac_ros
{
template <class ContainerAllocator>
struct SrvJdkResponse_
{
  typedef SrvJdkResponse_<ContainerAllocator> Type;

  SrvJdkResponse_()
    : count(0)  {
    }
  SrvJdkResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef uint32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::prac_ros::SrvJdkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prac_ros::SrvJdkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SrvJdkResponse_

typedef ::prac_ros::SrvJdkResponse_<std::allocator<void> > SrvJdkResponse;

typedef boost::shared_ptr< ::prac_ros::SrvJdkResponse > SrvJdkResponsePtr;
typedef boost::shared_ptr< ::prac_ros::SrvJdkResponse const> SrvJdkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prac_ros::SrvJdkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prac_ros::SrvJdkResponse_<ContainerAllocator1> & lhs, const ::prac_ros::SrvJdkResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prac_ros::SrvJdkResponse_<ContainerAllocator1> & lhs, const ::prac_ros::SrvJdkResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prac_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prac_ros::SrvJdkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prac_ros::SrvJdkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prac_ros::SrvJdkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac8b22eb02c1f433e0a55ee9aac59a18";
  }

  static const char* value(const ::prac_ros::SrvJdkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac8b22eb02c1f433ULL;
  static const uint64_t static_value2 = 0xe0a55ee9aac59a18ULL;
};

template<class ContainerAllocator>
struct DataType< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prac_ros/SrvJdkResponse";
  }

  static const char* value(const ::prac_ros::SrvJdkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 count\n"
;
  }

  static const char* value(const ::prac_ros::SrvJdkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvJdkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prac_ros::SrvJdkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prac_ros::SrvJdkResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRAC_ROS_MESSAGE_SRVJDKRESPONSE_H
