// Generated by gencpp from file prac_ros/timebackResult.msg
// DO NOT EDIT!


#ifndef PRAC_ROS_MESSAGE_TIMEBACKRESULT_H
#define PRAC_ROS_MESSAGE_TIMEBACKRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prac_ros
{
template <class ContainerAllocator>
struct timebackResult_
{
  typedef timebackResult_<ContainerAllocator> Type;

  timebackResult_()
    : success(false)
    , result_message()  {
    }
  timebackResult_(const ContainerAllocator& _alloc)
    : success(false)
    , result_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_message_type;
  _result_message_type result_message;





  typedef boost::shared_ptr< ::prac_ros::timebackResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prac_ros::timebackResult_<ContainerAllocator> const> ConstPtr;

}; // struct timebackResult_

typedef ::prac_ros::timebackResult_<std::allocator<void> > timebackResult;

typedef boost::shared_ptr< ::prac_ros::timebackResult > timebackResultPtr;
typedef boost::shared_ptr< ::prac_ros::timebackResult const> timebackResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prac_ros::timebackResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prac_ros::timebackResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prac_ros::timebackResult_<ContainerAllocator1> & lhs, const ::prac_ros::timebackResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.result_message == rhs.result_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prac_ros::timebackResult_<ContainerAllocator1> & lhs, const ::prac_ros::timebackResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prac_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prac_ros::timebackResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prac_ros::timebackResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prac_ros::timebackResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prac_ros::timebackResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prac_ros::timebackResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prac_ros::timebackResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prac_ros::timebackResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "653d7c58e227d73c141a202e6fd40f04";
  }

  static const char* value(const ::prac_ros::timebackResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x653d7c58e227d73cULL;
  static const uint64_t static_value2 = 0x141a202e6fd40f04ULL;
};

template<class ContainerAllocator>
struct DataType< ::prac_ros::timebackResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prac_ros/timebackResult";
  }

  static const char* value(const ::prac_ros::timebackResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prac_ros::timebackResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool success\n"
"string result_message\n"
;
  }

  static const char* value(const ::prac_ros::timebackResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prac_ros::timebackResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.result_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timebackResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prac_ros::timebackResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prac_ros::timebackResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRAC_ROS_MESSAGE_TIMEBACKRESULT_H
