// Generated by gencpp from file prac_ros/timebackAction.msg
// DO NOT EDIT!


#ifndef PRAC_ROS_MESSAGE_TIMEBACKACTION_H
#define PRAC_ROS_MESSAGE_TIMEBACKACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <prac_ros/timebackActionGoal.h>
#include <prac_ros/timebackActionResult.h>
#include <prac_ros/timebackActionFeedback.h>

namespace prac_ros
{
template <class ContainerAllocator>
struct timebackAction_
{
  typedef timebackAction_<ContainerAllocator> Type;

  timebackAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  timebackAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::prac_ros::timebackActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::prac_ros::timebackActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::prac_ros::timebackActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::prac_ros::timebackAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prac_ros::timebackAction_<ContainerAllocator> const> ConstPtr;

}; // struct timebackAction_

typedef ::prac_ros::timebackAction_<std::allocator<void> > timebackAction;

typedef boost::shared_ptr< ::prac_ros::timebackAction > timebackActionPtr;
typedef boost::shared_ptr< ::prac_ros::timebackAction const> timebackActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prac_ros::timebackAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prac_ros::timebackAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prac_ros::timebackAction_<ContainerAllocator1> & lhs, const ::prac_ros::timebackAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prac_ros::timebackAction_<ContainerAllocator1> & lhs, const ::prac_ros::timebackAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prac_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prac_ros::timebackAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prac_ros::timebackAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prac_ros::timebackAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prac_ros::timebackAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prac_ros::timebackAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prac_ros::timebackAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prac_ros::timebackAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "325a56ed416e9a3cfd892f8e5fc40db1";
  }

  static const char* value(const ::prac_ros::timebackAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x325a56ed416e9a3cULL;
  static const uint64_t static_value2 = 0xfd892f8e5fc40db1ULL;
};

template<class ContainerAllocator>
struct DataType< ::prac_ros::timebackAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prac_ros/timebackAction";
  }

  static const char* value(const ::prac_ros::timebackAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prac_ros::timebackAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"timebackActionGoal action_goal\n"
"timebackActionResult action_result\n"
"timebackActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: prac_ros/timebackActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"timebackGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: prac_ros/timebackGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 dish_count\n"
"\n"
"================================================================================\n"
"MSG: prac_ros/timebackActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"timebackResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: prac_ros/timebackResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool success\n"
"string result_message\n"
"\n"
"================================================================================\n"
"MSG: prac_ros/timebackActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"timebackFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: prac_ros/timebackFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 progress\n"
;
  }

  static const char* value(const ::prac_ros::timebackAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prac_ros::timebackAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timebackAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prac_ros::timebackAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prac_ros::timebackAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::prac_ros::timebackActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::prac_ros::timebackActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::prac_ros::timebackActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRAC_ROS_MESSAGE_TIMEBACKACTION_H
